### ISSUE TITLE
Could this be used along with redux? If so could you provide an example?

### ISSUE THREAD

**Issue by jeffbski** [roman01la/react-horizon#3]
I would think that for many use cases it might be nice to have a local redux store in addition to just having things connected directly. Not all state would necessarily go to horizon. 

If it would be possible to do so how might you incorporate it? (an example would be great).

If there are reasons you wouldn't want to use Redux then those could be documented as well since I imagine many people will have the same question.

I look forward to learning about your project, but I am also wondering at the same time whether it would be better to just be using Redux and having a sync (publish and subscribe) between parts of redux and horizon.  I am open to trying both approaches to see what makes the most sense.

**Comment by roman01la** [comment]
@jeffbski Hello. Could you give an example when you need remote state to be modified and stored locally? I mean, at least in my experience, usually you fetch data, maybe transform it and display. Later when you change data, it goes straight to backend.

But yes, `react-hz` can be used with Redux. In Redux there's `Provider` component and in React Horizon there's `HorizonProvider` component, you can use both together, like this:
```js
<Provider>
  <HorizonProvider>
<Provider>
```

**Comment by jeffbski** [comment]
Fantastic. Thanks for your work on this and the great explanation. I look forward to trying this out.
